### ISSUE TITLE
Time Slider

### ISSUE THREAD

**Issue by cstepper** [trafficonese/leaflet.extras2#1]
Hi, 
just found your package here on Github. 
We're currently working with movement data (including timestamps). I was just wondering, if you have any plans to integrate one of these ["Time Slider" Plugins](https://leafletjs.com/plugins#time--elevation). This would be a cool feature to use in our analysis
Cheers, Christoph

**Comment by tim-salabim** [comment]
@cstepper have you seen https://github.com/timelyportfolio/leaftime?

**Comment by trafficonese** [comment]
And the [LeafletPlayback](https://github.com/hallahan/LeafletPlaybackurl) is included in this package, although I'm not too happy about the implementation, but it works.

**Comment by tim-salabim** [comment]
+1 for the Leflet.Heightgraph plugin!

**Comment by trafficonese** [comment]
@cstepper is this solved for you, or would you need/prefer another Time-plugin?

**Comment by cstepper** [comment]
@trafficonese yes, this is solved from my side. I could work with the leaftime, which Tim recommended.

**Comment by wyuill** [comment]
Hi.

Thanks for creating leaflet.extras2 - nice to see some new features coming in. Could I cast another vote for "Time Slider" Plugins/reopen this issue? Time Slider is one of the few packages which allow selecting a time range rather than a single point in time. This is particularly a problem because there are issues with [crosstalk and dates](https://github.com/rstudio/crosstalk/issues/65) meaning the only option to select a date range that I'm aware of is to use shiny (with sharing implications) or predefine your date groupings as a checkbox (with obvious usage implications). I'm interested in this for mapping COVID-19 cases overtime and I can imagine there are a wide range of other use cases where one wants to look at events over a period of time esepically where those events may be less common (e.g. crime and accident mapping, examining multiple paths that occur over time to see common travel path).

Thanks

**Comment by trafficonese** [comment]
Do you mean [this plugin](https://github.com/dwilhelm89/LeafletSlider)? I will have a look at it.

**Comment by trafficonese** [comment]
Fortunately, that was much easier to implement than the playback plugin.
The dev version now has the function `addTimeslider`. I hope that fits your needs.

**Comment by wyuill** [comment]
Brillant thanks for doing this staggeringly fast.
