### ISSUE TITLE
Integrating GetLegendGraphic from Geoserver WMS Layers

### ISSUE THREAD

**Issue by amruthkiran94** [trafficonese/leaflet.extras2#62]
Hi! Thanks for the package!
I was looking to embed Geoserver-based legends on an R Shiny interface but couldn't find a way to do so. I was wondering if the `GetLegendGraphic` functionality would be implemented under the current `WMS` series of functions, considering `leaflet.extras` isn't maintained anymore. The `leaflet.wms` JS package mentions this request issue [here](https://github.com/heigeo/leaflet.wms/issues/4) as well, but it's been a while.

Any help would be great!
Thanks!

**Comment by trafficonese** [comment]
I will take over the `leaflet.extras` package and try to maintain it as best as I can.

I would therefore prefer to stick to the already implemented plugin there - https://github.com/kartoza/leaflet-wms-legend.

But getting the legend image is very simple via a GetLegendGraphic call.
The problem is more the customization of the Legend Image. (background/text-colors), especially if you have a shiny-app with dark/bright mode for example..

If you have the base URL of the geoserver and the layername, you could just use
```
  addControl(
    html = paste0("<img src=",
                  paste0(URL,
                         "?REQUEST=GetLegendGraphic&",
                         "FORMAT=image/png&tranparent=true&",
                         "LAYER=ws:layername"
                  ), ">"),
    position = "bottomright")
```

You can also add some LEGEND_OPTIONS:
`"&LEGEND_OPTIONS=fontColor:0x000033;fontSize:14;bgColor:0x000000"`
