### ISSUE TITLE
Timeslider documentation

### ISSUE THREAD

**Issue by jl5000** [trafficonese/leaflet.extras2#9]
I'm trying to get the timeslider functionality to work but there may be gaps in the documentation which are preventing me from getting something working.

For example, if I have a 6 row dataframe giving an attribute of two nodes at three specific time points (say, years), can I produce a map with a slider showing how this attribute (node colour) changes through time at these nodes? I'm ok with converting this to an sf points object and I'm using CircleMarkers.

**Comment by trafficonese** [comment]
Currently the function `addTimeslider` just uses the basic marker icon, so it wont work with CircleMarkers or icons. I will have a look at the styling options. 

But in the meantime, did you see the package [leaftime](https://github.com/timelyportfolio/leaftime), which might be better suited for your task?

**Comment by jl5000** [comment]
Thanks very much for your response. I hadn't heard of leaftime, so I'll check it out, thanks for the tip! :)

**Comment by trafficonese** [comment]
Taking a closer look at the underlying plugin, I think it should be possible to use circleMarkers and multiple groups. I found this [tutorial](https://github.com/geyerbri/LeafletSlider-tutorial#set-up-html-file-for-map), which should be quite useful for the adaptations needed.

**Comment by trafficonese** [comment]
I just pushed commit e83ae3d, which changes the markers to circleMarkers and allows styling of every point and popups.

Unfortunately, only 1 marker can be shown at a time. I didn't manage to implement the layerGroups and I'm not sure if this currently really possible.

**Comment by trafficonese** [comment]
The commit e313970 should fix the problem. I had to rewrite the underlying plugin a bit, but I think it is definitly worth it.

The example app [timeslider_app.R](https://github.com/trafficonese/leaflet.extras2/blob/master/inst/examples/timeslider_app.R) should reflect the new changes and is what you are looking for, I think. Could you check out the dev version and tell me if it solves your issue?

**Comment by jl5000** [comment]
Thanks for your hard work on this. I tried running the app but got an error message "Warning: Error in addTimeslider: unused arguments"

Would this fix work for a static HTML or does it require shiny?

**Comment by trafficonese** [comment]
It should work for static HTML aswell.

**Comment by trafficonese** [comment]
No, actually it didn't work because the `jquery-ui.css` used some .png files as background which markdown can't find.
I removed all those lines and it should work now.

I just tested with this markdown:

````
---
title: "An Interactive Map"
---

```{r include=FALSE}
library(leaflet)
library(leaflet.extras2)
library(sf)
library(shiny)

data <- sf::st_as_sf(leaflet::atlStorms2005)[1,]
data <- st_cast(data, "POINT")
data$time = as.POSIXct(seq.POSIXt(as.POSIXct(paste0(2020-nrow(data)+1,"-01-01")), 
                                  as.POSIXct("2020-01-01"), by = "year"))
data1 <- sf::st_as_sf(leaflet::atlStorms2005)[2,]
data1 <- st_cast(data1, "POINT")
data1$time = as.POSIXct(seq.POSIXt(as.POSIXct(paste0(2020-nrow(data1)+1,"-01-01")), 
                                   as.POSIXct("2020-01-01"), by = "year"))
data <- rbind(data, data1)

data$cols <- colourvalues::color_values(1:nrow(data))
data$wgt <- 1:nrow(data)
```

```{r out.width='100%', echo=FALSE}
leaflet() %>%
  addTiles() %>%
  addTimeslider(data = data, color = ~cols,
                popup = ~time,
                options = timesliderOptions(
                  sameDate = TRUE, 
                  alwaysShowDate = TRUE,
                  rezoom = FALSE))
```


````
